#!/usr/bin/env python3
"""
D2C YAML Utilities
YAML 处理和格式化工具
"""

import re
from typing import Any, Dict, Optional
import yaml


class MyDumper(yaml.Dumper):
    """
    自定义 YAML Dumper 类
    确保正确的缩进和格式
    """
    
    def increase_indent(self, flow: bool = False, indentless: bool = False):
        return super().increase_indent(flow, False)
    
    def write_line_break(self, data: Optional[str] = None) -> None:
        super().write_line_break(data)
        # 在顶级键之间添加空行
        if len(self.indents) == 1:
            super().write_line_break()


def clean_yaml_output(yaml_content: str) -> str:
    """
    清理 YAML 输出，移除不必要的空行和格式问题
    
    Args:
        yaml_content: 原始 YAML 内容
    
    Returns:
        清理后的 YAML 内容
    """
    # 移除行尾空格
    lines = [line.rstrip() for line in yaml_content.split('\n')]
    
    # 移除多余的连续空行
    result = []
    prev_empty = False
    
    for line in lines:
        is_empty = not line.strip()
        
        if is_empty:
            if not prev_empty:
                result.append(line)
            prev_empty = True
        else:
            result.append(line)
            prev_empty = False
    
    return '\n'.join(result)


def sanitize_compose_config(config: Dict[str, Any]) -> Dict[str, Any]:
    """
    清理 compose 配置，移除空值和默认值
    
    Args:
        config: compose 配置字典
    
    Returns:
        清理后的配置字典
    """
    if not isinstance(config, dict):
        return config
    
    result = {}
    
    for key, value in config.items():
        # 跳过 None 值
        if value is None:
            continue
        
        # 跳过空列表和空字典
        if isinstance(value, (list, dict)) and not value:
            continue
        
        # 递归处理嵌套字典
        if isinstance(value, dict):
            cleaned = sanitize_compose_config(value)
            if cleaned:  # 只添加非空字典
                result[key] = cleaned
        else:
            result[key] = value
    
    return result


def dump_compose_config(config: Dict[str, Any], 
                       clean: bool = True,
                       add_header: bool = True) -> str:
    """
    将 compose 配置转换为 YAML 字符串
    
    Args:
        config: compose 配置字典
        clean: 是否清理空值
        add_header: 是否添加生成信息头
    
    Returns:
        YAML 格式的字符串
    """
    if clean:
        config = sanitize_compose_config(config)
    
    # 使用自定义 Dumper 生成 YAML
    yaml_content = yaml.dump(
        config,
        Dumper=MyDumper,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
        indent=2,
        width=float('inf')
    )
    
    # 清理输出格式
    yaml_content = clean_yaml_output(yaml_content)
    
    # 添加生成信息头
    if add_header:
        header = """# Generated by Docker2Compose
# https://github.com/coracoo/docker2compose
# 
# 警告：此文件由程序自动生成，可能需要根据实际需求进行调整
#
"""
        yaml_content = header + yaml_content
    
    return yaml_content


# 自定义 YAML 表示器，处理特殊类型

def represent_str(dumper, data):
    """
    自定义字符串表示器
    如果字符串包含特殊字符，使用双引号
    """
    if '\n' in data:
        return dumper.represent_scalar('tag:yaml.org,2002:str', data, style='|')
    
    # 检查是否需要引号
    special_chars = [':', '#', '{', '}', '[', ']', ',', '&', '*', '?', '|', '-', '<', '>', '=', '!', '%', '@', '`', '"', "'"]
    needs_quotes = any(c in data for c in special_chars)
    
    if needs_quotes or data.startswith(('true', 'false', 'yes', 'no', 'on', 'off', 'null')):
        return dumper.represent_scalar('tag:yaml.org,2002:str', data, style='"')
    
    return dumper.represent_scalar('tag:yaml.org,2002:str', data)


def represent_none(dumper, _):
    """自定义 None 表示器"""
    return dumper.represent_scalar('tag:yaml.org,2002:null', '')


# 注册自定义表示器
MyDumper.add_representer(str, represent_str)
MyDumper.add_representer(type(None), represent_none)


if __name__ == '__main__':
    # 测试 YAML 工具
    test_config = {
        'services': {
            'web': {
                'image': 'nginx:latest',
                'container_name': 'my-web',
                'ports': ['80:80', '443:443'],
                'environment': {
                    'KEY': 'value with: special chars',
                    'EMPTY': None,
                },
                'volumes': [],  # 空列表应该被清理
            }
        },
        'networks': {},  # 空字典应该被清理
    }
    
    yaml_output = dump_compose_config(test_config, clean=True)
    print("生成的 YAML:")
    print(yaml_output)
